package com.fpt.backend.enums;

public enum PermissionModule {
    VIEW_TASKS,
    CREATE_TASKS,
    EDIT_TASKS,
    DELETE_TASKS,
    VIEW_DELIVERABLES,
    CREATE_DELIVERABLES,
    EDIT_DELIVERABLES,
    DELETE_DELIVERABLES,
    VIEW_CONTRACTS,
    EDIT_PROJECT,
    EDIT_PHASE,
    MANAGE_MEMBERS
}
