import { useMemo, useState } from "react";
import { Button, Card, Col, Form, Row, Table } from "react-bootstrap";
import {
    IconArrowLeft,
    IconArrowRight,
    IconCalendar,
    IconCheck,
    IconCircleCheck,
    IconDots,
    IconEye,
    IconFileInvoice,
    IconSearch,
    IconSignature,
    IconTrendingDown,
    IconTrendingUp,
    IconUpload,
} from "@tabler/icons-react";

const BLUE = "#1f5eff";
const NAVY = "#101a3e";
const MUTED = "#687694";
const BORDER = "#e7ebf3";
const agreements = [["Master Services Agreement", "Acme Corporation", "Active", "Service", "May 01, 2025", "May 01, 2026", "$125,000"], ["Software License Agreement", "Tech Solutions Inc.", "Active", "License", "Apr 15, 2025", "Apr 15, 2026", "$45,000"], ["NDA Agreement", "Blue Ltd.", "Active", "NDA", "May 10, 2025", "May 10, 2026", "$0"], ["Vendor Agreement", "Global Services LLC", "Active", "Vendor", "Apr 20, 2025", "Apr 20, 2026", "$75,000"], ["Service Agreement", "Innovatech Solutions", "Pending Signature", "Service", "May 18, 2025", "May 18, 2026", "$60,000"], ["Employment Agreement", "John Doe", "Pending Signature", "Employment", "May 20, 2025", "May 20, 2026", "$0"], ["Partnership Agreement", "Future Holdings", "Draft", "Partnership", "May 21, 2025", "May 21, 2026", "$0"], ["Consulting Agreement", "Bright Consulting", "Expired", "Service", "May 01, 2024", "May 01, 2025", "$30,000"]];

function TotalAgreements() {
    const [search, setSearch] = useState("");
    const [status, setStatus] = useState("All Status");
    const filtered = useMemo(() => agreements.filter((agreement) => agreement.join(" ").toLowerCase().includes(search.toLowerCase()) && (status === "All Status" || agreement[2] === status)), [search, status]);
    return <div className="bg-white" style={{ color: NAVY, fontFamily: "Inter, system-ui, -apple-system, BlinkMacSystemFont, 'Segoe UI', sans-serif" }}><div className="mb-4"><h1 className="fw-bold mb-1" style={{ fontSize: 25 }}>Total Agreements</h1><p className="mb-0" style={{ color: MUTED }}>View and manage all agreements in the system.</p></div><div className="d-flex flex-wrap align-items-center gap-3 mb-4"><SelectField value={status} onChange={setStatus} options={["All Status", "Active", "Pending Signature", "Draft", "Expired"]} style={{ minWidth: 266 }} /><SelectField icon={IconCalendar} value="May 1 – May 24, 2025" style={{ minWidth: 248 }} /><SearchField value={search} onChange={setSearch} className="ms-lg-auto" style={{ minWidth: 300 }} /><Button variant="outline-primary" className="d-flex align-items-center gap-2 px-3" style={{ minHeight: 42, borderColor: "#87a7ff", color: BLUE }}><IconUpload size={18} />Export</Button></div><Row className="g-3 mb-4"><Col xl={3} md={6}><MetricCard label="Total Agreements" value="1,248" change="12.5%" icon={IconFileInvoice} tone="blue" /></Col><Col xl={3} md={6}><MetricCard label="Active Agreements" value="856" change="8.2%" icon={IconCircleCheck} tone="green" /></Col><Col xl={3} md={6}><MetricCard label="Pending Signatures" value="128" change="6.3%" icon={IconSignature} tone="orange" /></Col><Col xl={3} md={6}><MetricCard label="Expired Agreements" value="24" change="4.0%" direction="down" icon={IconCalendar} tone="red" /></Col></Row><AgreementsTable rows={filtered} /></div>;
}

function SelectField({ value, onChange, options, icon: Icon, style }) { return <div className="position-relative" style={style}>{Icon && <Icon className="position-absolute top-50 translate-middle-y" style={{ left: 16, color: "#3d4b68", zIndex: 1 }} size={18} />}<Form.Select value={value} onChange={(event) => onChange?.(event.target.value)} className={`fw-medium ${Icon ? "ps-5" : "ps-3"}`} style={{ height: 42, borderColor: "#dce3ee", color: "#2d3c5d", fontSize: 13 }}>{(options || [value]).map((option) => <option key={option}>{option}</option>)}</Form.Select></div>; }
function SearchField({ value, onChange, className, style }) { return <div className={`position-relative ${className}`} style={style}><IconSearch className="position-absolute top-50 translate-middle-y" style={{ left: 15, color: "#4c5b78", zIndex: 1 }} size={19} /><Form.Control value={value} onChange={(event) => onChange(event.target.value)} placeholder="Search agreements, parties, or tags..." className="ps-5" style={{ height: 42, borderColor: "#dce3ee", fontSize: 13 }} /></div>; }
function MetricCard({ label, value, change, direction = "up", icon: Icon, tone }) { const tones = { blue: ["#eaf0ff", BLUE], green: ["#e5f8ef", "#08b875"], orange: ["#fff3e4", "#ff8500"], red: ["#ffebed", "#f3273b"] }; const [background, color] = tones[tone]; const ChangeIcon = direction === "down" ? IconTrendingDown : IconTrendingUp; return <Card className="h-100 border shadow-sm" style={{ borderColor: BORDER, borderRadius: 10 }}><Card.Body className="p-4"><div className="d-flex justify-content-between align-items-start mb-2"><span style={{ color: "#52617e" }}>{label}</span><span className="rounded-3 d-flex align-items-center justify-content-center" style={{ width: 54, height: 54, color, background }}><Icon size={27} /></span></div><div className="d-flex align-items-center gap-3 mt-1"><span className="fw-bold" style={{ fontSize: 27 }}>{value}</span><span className="fw-semibold d-inline-flex align-items-center gap-1" style={{ color: direction === "down" ? "#f3273b" : "#08ac68" }}><ChangeIcon size={17} />{change}</span></div><div className="mt-2" style={{ color: MUTED, fontSize: 13 }}>vs Apr 1 – Apr 30, 2025</div></Card.Body></Card>; }
function StatusBadge({ status }) { if (status === "Active") return <span className="d-inline-flex align-items-center gap-1 rounded-2" style={{ padding: "5px 9px", background: "#e9f8ef", color: "#08a965" }}><IconCheck size={14} stroke={3} />Active</span>; if (status === "Pending Signature") return <span className="rounded-2 fw-semibold" style={{ padding: "6px 10px", background: "#fff4e8", color: "#ff8500" }}>Pending Signature</span>; if (status === "Expired") return <span className="rounded-2 fw-semibold" style={{ padding: "6px 10px", background: "#ffedef", color: "#f12f43" }}>Expired</span>; return <span className="rounded-2" style={{ padding: "5px 9px", background: "#eff2f6", color: "#52617e" }}>● Draft</span>; }
function Actions() { return <div className="d-flex gap-2"><button type="button" className="btn btn-sm bg-white border" aria-label="View agreement" style={{ borderColor: "#dce3ee" }}><IconEye size={17} /></button><button type="button" className="btn btn-sm bg-white border" aria-label="More actions" style={{ borderColor: "#dce3ee" }}><IconDots size={17} /></button></div>; }
function AgreementsTable({ rows }) { const headers = ["Agreement Name", "Party", "Status", "Type", "Effective Date", "Expiry Date", "Value", "Actions"]; return <Card className="border shadow-sm overflow-hidden" style={{ borderColor: BORDER, borderRadius: 10 }}><Card.Body className="p-0"><div className="p-4 border-bottom" style={{ borderColor: BORDER }}><h2 className="h6 fw-bold mb-0">All Agreements (1,248)</h2></div><div className="table-responsive"><Table className="align-middle mb-0" style={{ minWidth: 1050, fontSize: 13 }}><thead style={{ background: "#fafbfe", color: "#3d4a67" }}><tr>{headers.map((header) => <th key={header} className="fw-semibold text-nowrap px-4 py-3">{header}</th>)}</tr></thead><tbody>{rows.map((row) => <tr key={row[0]}>{row.map((value, index) => <td key={`${row[0]}-${index}`} className={`px-4 py-3 text-nowrap ${index === 0 ? "fw-semibold" : ""}`}>{index === 2 ? <StatusBadge status={value} /> : value}</td>)}<td className="px-4 py-2"><Actions /></td></tr>)}</tbody></Table></div><div className="d-flex flex-wrap gap-3 justify-content-between align-items-center px-4 py-3 border-top" style={{ color: MUTED, borderColor: BORDER, fontSize: 13 }}><span>Showing {rows.length ? 1 : 0} to {rows.length} of 1,248 results</span><div className="d-flex align-items-center gap-2"><IconArrowLeft size={16} /><button type="button" className="btn btn-sm border" style={{ width: 36, height: 36, borderColor: "#8ba9ff", color: BLUE }}>1</button>{["2", "3", "4", "5", "…", "156"].map((page) => <button type="button" key={page} className="btn btn-sm border-0">{page}</button>)}<IconArrowRight size={16} /></div></div></Card.Body></Card>; }

export default TotalAgreements;
